/** @type {import('tailwindcss').Config} */
// Design tokens from the Kunjachaya Club Stitch design system —
// stitch_kunjachaya_resident_club_app/kunjachaya_resident_club_design_system/DESIGN.md
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#386b01',
        'surface-container-high': '#e9e8e2',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#0d2000',
        'on-surface': '#1b1c18',
        'inverse-surface': '#30312c',
        'on-surface-variant': '#42493a',
        'on-error': '#ffffff',
        'surface-tint': '#386b00',
        'tertiary': '#1f4e50',
        'background': '#fafaf3',
        'surface': '#fafaf3',
        'on-tertiary-fixed': '#002021',
        'tertiary-fixed-dim': '#a0cfd1',
        'on-tertiary-fixed-variant': '#1f4d50',
        'secondary-container': '#d6e4c8',
        'on-primary-container': '#aeea79',
        'on-secondary-container': '#596750',
        'surface-variant': '#e3e3dc',
        'surface-bright': '#fafaf3',
        'on-primary-fixed-variant': '#285000',
        'surface-container-low': '#f5f4ed',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#bdcbb0',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#3e4a36',
        'on-background': '#1b1c18',
        'primary': '#295100',
        'surface-container': '#efeee7',
        'inverse-primary': '#9cd768',
        'on-primary': '#ffffff',
        'primary-fixed': '#b7f481',
        'secondary': '#55624c',
        'outline': '#727a69',
        'surface-container-highest': '#e3e3dc',
        'inverse-on-surface': '#f2f1ea',
        'on-secondary': '#ffffff',
        'tertiary-container': '#396668',
        'on-secondary-fixed': '#131f0d',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#bcebed',
        'secondary-fixed': '#d9e7cb',
        'on-tertiary-container': '#b3e2e4',
        'error': '#ba1a1a',
        'surface-dim': '#dbdad4',
        'primary-fixed-dim': '#9cd768',
        'outline-variant': '#c2c9b6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        md: '16px',
        gutter: '16px',
        'container-padding': '16px',
        sm: '8px',
        lg: '24px',
        xl: '32px',
        base: '4px',
      },
      fontFamily: {
        display: ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Be Vietnam Pro', 'sans-serif'],
        'label-sm': ['Be Vietnam Pro', 'sans-serif'],
        'body-md': ['Be Vietnam Pro', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'title-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Be Vietnam Pro', 'sans-serif'],
        sans: ['Be Vietnam Pro', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.25px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'title-lg': ['22px', { lineHeight: '28px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
